### ISSUE TITLE
ignoreActions config doesn't seem to work?

### ISSUE THREAD

**Issue by DomHynes** [appsignal/appsignal-nodejs#315]
I'm trying to get my healthcheck disabled but the ignoreActions config doesn't seem to be blocking the action from being sent.

I'm using NestJS, and adding the express middleware right before I boot the application.
![image](https://user-images.githubusercontent.com/13274907/97547667-2e202180-1a22-11eb-8635-404ead600398.png)

This is my configuration:
![image](https://user-images.githubusercontent.com/13274907/97547421-e7cac280-1a21-11eb-8eae-290c6c44f7ef.png)

But the health action is still very much being sent:
![image](https://user-images.githubusercontent.com/13274907/97547500-fd3fec80-1a21-11eb-8c46-d5ac50dce30c.png)

Not sure if I've missed something in the documentation here.

**Comment by xadamy** [comment]
@DomHynes Hey there! Apologies for the late reply, I've been on holiday for the past two weeks so this is the first opportunity I've had to take a look at this issue. Looks like you're correct - the actions aren't being ignored, so it looks like we might have broken something in the agent. Let me take a look and get back to you once I've found a fix.

To @DomHynes and anyone else reading this: if you've been affected by this issue, please ping our support team at support@appsignal.com, as we don't want to charge you for any potential overage caused by this bug for as long as this issue remains open.

**Comment by DomHynes** [comment]
Just shot off an email to support, thanks for the assistance!

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700015185

**Comment by xadamy** [comment]
@DomHynes Thank you for your patience! I can confirm that this should now be working in `@appsignal/nodejs@1.0.2`!
