### ISSUE TITLE
Integration tests for integrations in a build matrix

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-nodejs#389]
For each integration, there should be at least one integration test that spins up an example application and does a request. We can then test the results of that request by inspecting the JSON span representation from the extension. We’ll set up a build matrix to test the integrations across supported versions of our integrations.

**Comment by tombruijn** [comment]
To fix the issue I was talking about in the call I'm thinking of:

The integration example test apps currently don't run `npm install` in their app directory. Somehow (without error or warning) the apps rely on the versions of the packages installed in the root of the repo. Which seems to work, but is weird, and we wouldn't need the example app's `package.json` for that. It will probably break if the example app's `package.json` lists a dependency that isn't part of the root `package.json`.

Moving all the development dependencies to the packages themselves, rather than have them in the root `package.json` will help organize things a bit. For my brain that would make more sense, but I don't know if it would for the entire project. We'd need to see what would happen with the different versions of packages we install in the CI build.

It would also help with different test setups where we may need to use a different combination of packages (or more packages) that we don't want to always have installed in the root of the project.

**Comment by tombruijn** [comment]
Fixes for the problems I described in my previous comment are made in PR https://github.com/appsignal/appsignal-nodejs/pull/431

**Comment by tombruijn** [comment]
I'm actually going to close this as the last PR for this is created: https://github.com/appsignal/appsignal-nodejs/pull/433
