### ISSUE TITLE
The filterParameters config option is not implemented

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#486]
## The problem

The filterParameters option is listed in [the Node.js config options docs](https://docs.appsignal.com/nodejs/configuration/options.html#option-filterparameters), but there's no implementation at all in the integration.

Users can set it up, but it won't affect the AppSignal parameters sanitation. In the other integrations, if values are set up for this option, all defined request parameters are filtered out, so they are not shown in the app.

Other integrations:

- [Ruby gem's HashSanitizer](https://github.com/appsignal/appsignal-ruby/blob/main/lib/appsignal/utils/hash_sanitizer.rb)
- [Elixir package's MapFilter](https://github.com/appsignal/appsignal-elixir/blob/main/lib/appsignal/utils/map_filter.ex)

Node.js integration:
- General incoming HTTP requests are wrapped here: https://github.com/appsignal/appsignal-nodejs/blob/main/packages/nodejs/src/instrumentation/http/lifecycle/incoming.ts
- Express handles them here: https://github.com/appsignal/appsignal-nodejs/blob/main/packages/express/src/middleware/index.ts

## The proposal

The config options and diagnose tests already support `filterParameter`, so we can focus on the implementation.

- [x] Implement parameter filtering for general HTTP requests in the Node.js core package
- [x] Implement parameter filtering for Express package
- [ ] Update the diagnose tests to match with these new default filtered parameters
- [ ] Update the docs to show a list of suggested filtered parameters to the user:
  - `password`
  - `email`
  - `token`
  - `api_token`

**Comment by tombruijn** [comment]
From what I can tell from the Elixir integration, the `filter_parameters` and `filter_session_data` options should be merged into the `filter_data_keys` option.

But as we established in https://github.com/appsignal/integration-guide/issues/31 we don't actually want to do that anymore in the long term.

We should work to fix it in the Node.js integration as it works in the Elixir integration, because it's a quicker fix than the linked issue, and we may send data now that we do not want to send.

**Comment by tombruijn** [comment]
> Add a list of default parameters to filter: 

We do not provide a default list of parameters for any other integration. If we want to do that, it should be a separate issue on the integrations guide.

**Comment by luismiramirez** [comment]
> > Add a list of default parameters to filter:
> 
> We do not provide a default list of parameters for any other integration. If we want to do that, it should be a separate issue on the integrations guide.

What we do now is to provide a suggested list to users in the docs. I understand, we can make that a separate issue for the 3 integrations.

**Comment by tombruijn** [comment]
> What we do now is to provide a suggested list to users in the docs.

Where we provide that suggestion?

**Comment by luismiramirez** [comment]
> Where we provide that suggestion?

Here: https://docs.appsignal.com/ruby/configuration/options.html#option-filter_session_data

**Comment by tombruijn** [comment]
The filter_parameters option has been implemented in https://github.com/appsignal/appsignal-nodejs/pull/502
I've checked off these two items from the list, because the filtering has been implemented in the extension and the Node.js integration will now configure the extension with what fields to filter out.

- Implement parameter filtering for general HTTP requests in the Node.js core package
- Implement parameter filtering for Express package

**Comment by tombruijn** [comment]
About the default parameter options to filter out, we've created issue: https://github.com/appsignal/integration-guide/issues/81
Closing this one.
