### ISSUE TITLE
Throws "AppSignal extension not loaded" when using @appsignal/koa with Strapi

### ISSUE THREAD

**Issue by sercanov** [appsignal/appsignal-nodejs#634]
I wanted to give it a try. I see Strapi isn't officially supported but under the hood it uses Koa so I followed Koa installation instructions. 

Integrated like below and got this error. Any ideas? 

<img width="950" alt="image" src="https://user-images.githubusercontent.com/10291644/160303366-c12e9533-9ed6-4d92-be65-0f98911c5edb.png">

**Comment by tombruijn** [comment]
Hi @sercanov,

This usually means something went wrong during the installation. Can you run the diagnose command on the host you see this log message?
https://docs.appsignal.com/nodejs/command-line/diagnose.html

Please send the diagnose support token to support@appsignal.com so that we can take a look.
Also include the link to this issue.

**Comment by shairyar** [comment]
Diagnose report is available [here](https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700101771) (private link)

**Comment by tombruijn** [comment]
Issue was related to python not being found. We updated node-gyp and updated our docs. We can no longer rely on homebrew python so we suggest installing python through a python version manager.
