### ISSUE TITLE
When running in docker, we get "AppSignal extension not loaded."

### ISSUE THREAD

**Issue by matiasgarcia** [appsignal/appsignal-nodejs#654]
We are having an strange issue where in our localhost we can test the connection to Appsignal without any issues.

However, when we build a docker image and start it, we get the following error with no trace at all of what's the problem:

> AppSignal extension not loaded. This could mean that your current environment isn't supported, or that another error has occurred.

Our appsignal.ts file is configured the following way:

```
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { env } from './config/env';
import { Appsignal, Span } from '@appsignal/nodejs';
import { NextFunction, Request, Response } from 'express';

export const appsignal = new Appsignal({
    active: env.APP_SIGNAL_ENV === 'production' || env.APP_SIGNAL_ENV === 'staging',
    name: env.APP_SIGNAL_APP_NAME,
    pushApiKey: env.APP_SIGNAL_API_KEY,
    environment: env.APP_SIGNAL_ENV,
    log: 'stdout',
    logLevel: "debug",
    revision: env.APP_SIGNAL_APP_REVISION,
    requestHeaders: [
        "accept",
        "accept-charset",
        "accept-encoding",
        "accept-language",
        "cache-control",
        "connection",
        "content-length",
        "range",
        "x-exchange-user-id",
    ]
});

if (env.APP_SIGNAL_TEST){
    appsignal.demo()
}
```

We are using appsignal/nodejs@2.3.2 with appsignal/core@1.1.16 and appsignal/express@1.0.26

**Comment by tombruijn** [comment]
Hi @matiasgarcia, it's probably that the extension installed for your local system, but then when the node_modules is mounted in your docker container it can't start the extension, because it's for another kind of system (e.g. macOS vs Linux). Please either don't mount node_modules and run `npm/yarn install` in the container. Or run `npm run clean && npm run install` in the `node_modules/@appsignal/nodejs` directory before running your app to install the right extension for you container.

You can verify the above by running the diagnose tool in your container and looking at the results on AppSignal.com after sending it. We can also take a look with you if you send the token to support@appsignal.com and mention this issue.

Related issue for Elixir: https://github.com/appsignal/appsignal-elixir/issues/254

**Comment by matiasgarcia** [comment]
Thanks @tombruijn. Didn't know about the diagnose tool. Indeed the problem was the we were missing some system dependencies in the docker image. Closing this.
